/**
 * This file is automatically generated by scripts/generate-parsers.js
 *
 * ⚠️ DO NOT MODIFY MANUALLY!
 * Add or remove parser files in the src/utils/parsers directory,
 * and this file will be automatically updated when running npm run dev or npm run deploy.
 */
import type { SiteParser } from "../../config";
import { apodParser } from "./apod";
import { defaultParser } from "./default";
import { iplaysoftParser } from "./iplaysoft";
import { sspaiParser } from "./sspai";
import { yahooNewsByProviderParser } from "./yahoonews";

/** Parser mapping table */
const parsers: Record<string, SiteParser> = {
  apod: apodParser,
  default: defaultParser,
  iplaysoft: iplaysoftParser,
  sspai: sspaiParser,
  yahooNewsByProvider: yahooNewsByProviderParser,
};

/**
 * Get a parser by name
 * Fallback to default if no parser is found
 */
export function getParser(name: string): SiteParser {
  return parsers[name] || parsers["default"];
}
