/**
 * This file is automatically generated by scripts/generate-parsers.js
 *
 * ⚠️ DO NOT MODIFY MANUALLY!
 * Add or remove parser files in the src/utils/parsers directory,
 * and this file will be updated automatically when running npm run dev or npm run deploy.
 */
import type { SiteParser } from "../../config";
import { apodParser } from "./apod";
import { defaultParser } from "./default";

/** Parser mapping table */
const parsers: Record<string, SiteParser> = {
  apod: apodParser,
  default: defaultParser,
};

/**
 * Get parser by name
 * Fallback to default if the specified parser is not found
 */
export function getParser(name: string): SiteParser {
  return parsers[name] || parsers["default"];
}
