const fs = require('fs');
const path = require('path');

const parsersDir = path.join(__dirname, '../src/utils/parsers');
const indexFile = path.join(parsersDir, 'index.ts');

function generate() {
    console.log('[Pre-build] Generating parsers/index.ts...');

    if (!fs.existsSync(parsersDir)) {
        console.warn(`[Pre-build] Directory not found: ${parsersDir}`);
        return;
    }

    const files = fs.readdirSync(parsersDir);
    const parserFiles = files.filter(file => file.endsWith('.ts') && file !== 'index.ts' && !file.endsWith('.test.ts'));

    let imports = `import type { SiteParser } from '../../config';\n`;
    let parsersObj = `\n/** Parser mapping table */\nconst parsers: Record<string, SiteParser> = {\n`;

    for (const file of parserFiles) {
        const name = file.replace('.ts', '');
        // Convert to camelCase and add Parser suffix
        // Example: apod.ts -> apodParser, my-site.ts -> mySiteParser
        const camelName = name.replace(/-([a-z])/g, g => g[1].toUpperCase());
        const exportName = `${camelName}Parser`;

        imports += `import { ${exportName} } from './${name}';\n`;
        parsersObj += `    '${name}': ${exportName},\n`;
    }

    parsersObj += `};\n`;

    const targetContent = `/**
 * This file is automatically generated by scripts/generate-parsers.js
 * 
 * ⚠️ DO NOT MODIFY MANUALLY!
 * Add or remove parser files in the src/utils/parsers directory,
 * and this file will be automatically updated when running npm run dev or npm run deploy.
 */
${imports}
${parsersObj}
/**
 * Get a parser by name
 * Fallback to default if no parser is found
 */
export function getParser(name: string): SiteParser {
    return parsers[name] || parsers['default'];
}
`;

    fs.writeFileSync(indexFile, targetContent);
    console.log('[Pre-build] Successfully generated src/utils/parsers/index.ts!');
}

generate();
