const fs = require("fs");
const path = require("path");

const parsersDir = path.join(__dirname, "../src/utils/parsers");
const indexFile = path.join(parsersDir, "index.ts");

function generate() {
  console.log("[Pre-build] Generating parsers/index.ts...");

  if (!fs.existsSync(parsersDir)) {
    console.warn(`[Pre-build] Directory not found: ${parsersDir}`);
    return;
  }

  const getAllTsFiles = (dir, fileList = []) => {
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const filePath = path.join(dir, file);
      if (fs.statSync(filePath).isDirectory()) {
        getAllTsFiles(filePath, fileList);
      } else if (
        file.endsWith(".ts") &&
        file !== "index.ts" &&
        !file.endsWith(".test.ts")
      ) {
        fileList.push(filePath);
      }
    }
    return fileList;
  };

  const parserFiles = getAllTsFiles(parsersDir);

  let imports = `import type { SiteParser } from '../../config';\n`;
  let parsersObj = `\n/** Parser mapping table */\nconst parsers: Record<string, SiteParser> = {\n`;

  for (const filePath of parserFiles) {
    const content = fs.readFileSync(filePath, "utf-8");
    let importPath =
      "./" +
      path
        .relative(parsersDir, filePath)
        .replace(/\\/g, "/")
        .replace(/\.ts$/, "");

    // Match export const <something>Parser
    const regex = /export\s+const\s+([a-zA-Z0-9_]+)Parser\s*(:|=)/g;
    let match;
    while ((match = regex.exec(content)) !== null) {
      const camelName = match[1];
      const exportName = `${camelName}Parser`;

      imports += `import { ${exportName} } from '${importPath}';\n`;
      parsersObj += `    '${camelName}': ${exportName},\n`;
    }
  }

  parsersObj += `};\n`;

  const targetContent = `/**
 * This file is automatically generated by scripts/generate-parsers.js
 * 
 * ⚠️ DO NOT MODIFY MANUALLY!
 * Add or remove parser files in the src/utils/parsers directory,
 * and this file will be automatically updated when running npm run dev or npm run deploy.
 */
${imports}
${parsersObj}
/**
 * Get a parser by name
 * Fallback to default if no parser is found
 */
export function getParser(name: string): SiteParser {
    return parsers[name] || parsers['default'];
}
`;

  fs.writeFileSync(indexFile, targetContent);
  console.log("[Pre-build] Successfully generated src/utils/parsers/index.ts!");
}

generate();
